# Generated by Django 4.1.5 on 2023-01-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
