# Generated by Django 4.1.5 on 2023-01-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('KWD', 'KWD'), ('BHD', 'BHD'), ('OMR', 'OMR'), ('JOD', 'JOD'), ('GBP', 'GBP'), ('KYD', 'KYD'), ('EUR', 'EUR'), ('CHF', 'CHF'), ('USD', 'USD'), ('CAD', 'CAD')], default='USD', max_length=10),
        ),
    ]
