# Generated by Django 4.1.5 on 2023-01-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('KWD', 'KWD'), ('BHD', 'BHD'), ('OMR', 'OMR'), ('JOD', 'JOD'), ('GBP', 'GBP'), ('KYD', 'KYD'), ('EUR', 'EUR'), ('CHF', 'CHF'), ('USD', 'USD'), ('CAD', 'CAD')], max_length=10),
        ),
    ]
