# Generated by Django 4.1.5 on 2023-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_income_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
