# Generated by Django 4.1.5 on 2023-01-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_income_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='name',
        ),
        migrations.AddField(
            model_name='income',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Saving', 'Saving')], max_length=50)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.income')),
            ],
        ),
    ]
