# Generated by Django 4.1.5 on 2023-01-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_income_name_income_income_expense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Outlay',
        ),
    ]
